<div class="social-media">
   <?php if($this->getFacebookUrl()): ?>
        <a class="facebook" href="<?php echo $this->getFacebookUrl() ?>">Facebook</a>
   <?php endif ?>

    <?php if($this->getTwitterUrl()): ?>
        <a class="twitter" href="<?php echo $this->getTwitterUrl() ?>">Twitter</a>
    <?php endif ?>

    <?php if($this->getGooglePlusUrl()): ?>
        <a class="google-plus" href="<?php echo $this->getGooglePlusUrl() ?>">Google plus</a>
    <?php endif ?>
</div>

<!--<reference name="content">
  <block type="core/template" name="social" template="page/social-links.phtml">
    <action method="setData"><name>facebook_url</name><value>facebookurl</value></action>
    <action method="setData"><name>twitter_url</name><value>http://twitter.com/inviqa</value></action>
  </block>
</reference>
-->



<!--
<reference name="content">
  <block type="core/template" name="social" template="page/social-links.phtml">
    <action method="setData"><name>facebook_url</name><value>facebookurl</value></action>
    <action method="setData"><name>twitter_url</name><value>http://twitter.com/inviqa</value></action>
  </block>
  
  <action method="unsetChild"  ifconfig="web/sociallinks/enable_sociallinks">
    <child>social</child>
  </action>
</reference>
-->
